[package]
name = "space_kit"
version = "0.1.0"
authors = ["Dalton Claybrook <daltonclaybrook@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

astro = "2.0.0"
